/**
 * Credits store — freemium credit system
 *
 * - 2000 credits on signup (= 2000 words)
 * - 1 credit = 1 word generated by Oracle
 * - Active subscription → credits NOT consumed
 */
import { Platform } from 'react-native';
import { create } from 'zustand';
import { http } from '../services/http.client';
import { StorageService } from '../services/storage.service';

/** Notification push locale quand les crédits tombent à 0 */
async function sendLowCreditsNotification() {
  const title = '⚡ Oracle Plus — Crédits épuisés';
  const body  = 'Vos crédits sont épuisés. Rechargez ou abonnez-vous pour continuer à recevoir vos guidances spirituelles.';
  try {
    if (Platform.OS !== 'web') {
      const Notifs = await import('expo-notifications');
      await Notifs.scheduleNotificationAsync({
        content: {
          title,
          body,
          sound: true,
          data: { url: '/subscription' },
          ...(Platform.OS === 'android' ? { priority: 'high', vibrate: [0, 250, 250, 250] } : {}),
        },
        trigger: null,
      });
    } else if (typeof window !== 'undefined' && 'Notification' in window && Notification.permission === 'granted') {
      const options: NotificationOptions = {
        body,
        icon: '/icon-192.png',
        badge: '/favicon.png',
        tag: 'low-credits',
        requireInteraction: true,
        vibrate: [200, 100, 200],
        data: { url: '/subscription' },
        actions: [
          { action: 'recharge', title: 'Recharger maintenant' },
          { action: 'subscribe', title: "S'abonner" },
        ],
      } as any;
      if ('serviceWorker' in navigator) {
        const reg = await navigator.serviceWorker.ready;
        await reg.showNotification(title, options);
      } else {
        new Notification(title, options);
      }
    }
  } catch {
    // Silencieux
  }
}

const CREDITS_KEY = '@oracle/credits';
const ADS_KEY = '@oracle/ads_today';
export const INITIAL_CREDITS = 2000;

export const CREDIT_COSTS = {
  ai_chat:                 50,
  accompagnement:          50,
  dream_interpretation:    80,
  prophetic_consultation: 100,
  prayer_generation:       20,
  audio_preview:           10,
  audio_full:              50,
} as const;

export type CreditAction = keyof typeof CREDIT_COSTS;

export const CREDIT_PACKS = [
  { id: 'starter',  label: 'Pack Départ',   credits: 500,  price: 500,  priceLabel: '500 FCFA' },
  { id: 'standard', label: 'Pack Standard', credits: 2000, price: 1000, priceLabel: '1 000 FCFA', badge: '⭐ Populaire' },
  { id: 'premium',  label: 'Pack Premium',  credits: 5000, price: 2500, priceLabel: '2 500 FCFA', badge: '🏆 Meilleure valeur' },
] as const;

export type CreditPackId = typeof CREDIT_PACKS[number]['id'];

interface CreditsState {
  credits: number;
  adsAvailable: number;
  isLoading: boolean;
  init: () => Promise<void>;
  fetchBalance: () => Promise<void>;
  spend: (action: CreditAction) => Promise<boolean>;
  /** Deduct exactly `wordCount` credits (1 credit = 1 word). Returns false if insufficient. */
  spendWords: (wordCount: number) => Promise<boolean>;
  adReward: () => Promise<void>;
  purchase: (packId: CreditPackId | string, reference: string) => Promise<void>;
  canAfford: (action: CreditAction) => boolean;
  setCredits: (n: number) => void;
}

export const useCreditsStore = create<CreditsState>((set, get) => ({
  credits: INITIAL_CREDITS,
  adsAvailable: 3,
  isLoading: false,

  init: async () => {
    const cached = await StorageService.get<number>(CREDITS_KEY);
    if (cached !== null) set({ credits: cached });
    await get().fetchBalance();
  },

  fetchBalance: async () => {
    try {
      // Essayer plusieurs routes selon la version du backend
      let res: any = null;
      try { res = await http.get<any>('/credits/me'); } catch {}
      if (!res?.credits && res?.credits !== 0) {
        try { res = await http.get<any>('/credits'); } catch {}
      }
      if (res?.credits !== undefined) {
        set({ credits: res.credits, adsAvailable: res.adsAvailable ?? res.adsRemaining ?? 3 });
        await StorageService.set(CREDITS_KEY, res.credits);
      }
    } catch { /* offline — keep local cache */ }
  },

  spend: async (action: CreditAction): Promise<boolean> => {
    const cost = CREDIT_COSTS[action];
    if (get().credits < cost) return false;
    // Déduire localement immédiatement pour une UX réactive
    const optimistic = get().credits - cost;
    set({ credits: optimistic });
    await StorageService.set(CREDITS_KEY, optimistic);
    try {
      // Essayer plusieurs routes selon la version du backend
      let res: any = null;
      try { res = await http.post<{ credits: number }>('/credits/deduct', { amount: cost, action }); } catch {}
      if (!res) {
        try { res = await http.post<{ credits: number }>('/credits/spend', { amount: cost, description: action }); } catch {}
      }
      if (res?.credits !== undefined) {
        set({ credits: res.credits });
        await StorageService.set(CREDITS_KEY, res.credits);
      }
    } catch { /* déjà déduit localement */ }
    return true;
  },

  spendWords: async (wordCount: number): Promise<boolean> => {
    if (wordCount <= 0) return true;
    if (get().credits < wordCount) return false;
    const optimistic = get().credits - wordCount;
    set({ credits: optimistic });
    await StorageService.set(CREDITS_KEY, optimistic);
    try {
      let res: any = null;
      try { res = await http.post<{ credits: number }>('/credits/deduct', { amount: wordCount, action: 'word_generation' }); } catch {}
      if (!res) {
        try { res = await http.post<{ credits: number }>('/credits/spend', { amount: wordCount, description: 'word_generation' }); } catch {}
      }
      if (res?.credits !== undefined) {
        set({ credits: res.credits });
        await StorageService.set(CREDITS_KEY, res.credits);
      }
    } catch {}
    if (get().credits <= 0) sendLowCreditsNotification();
    return true;
  },

  adReward: async () => {
    try {
      let res: any = null;
      try { res = await http.post<{ credits: number }>('/credits/ad-reward', {}); } catch {}
      if (!res) {
        try { res = await http.post<{ credits: number }>('/credits/add', { amount: 100 }); } catch {}
      }
      if (res?.credits !== undefined) {
        set({ credits: res.credits, adsAvailable: res.adsRemaining ?? Math.max(0, get().adsAvailable - 1) });
        await StorageService.set(CREDITS_KEY, res.credits);
        return;
      }
    } catch {}
    // Fallback local
    const next = get().credits + 100;
    const ads = Math.max(0, get().adsAvailable - 1);
    set({ credits: next, adsAvailable: ads });
    await StorageService.set(CREDITS_KEY, next);
  },

  purchase: async (packId, reference) => {
    // 1. Notifier le backend — essayer plusieurs clés selon la version
    try {
      await http.post('/credits/purchase', { pack: packId, packId, reference });
    } catch {
      try { await http.post(`/subscriptions/verify/${reference}`, {}); } catch {}
    }
    // 2. Resynchroniser le solde depuis le backend (source de vérité)
    await get().fetchBalance();
  },

  canAfford: (action: CreditAction): boolean => get().credits >= CREDIT_COSTS[action],

  setCredits: (n: number) => set({ credits: n }),
}));
