/**
 * Credits store — freemium credit system
 *
 * - 2000 credits on signup (= 2000 words)
 * - 1 credit = 1 word generated by Oracle
 * - Active subscription → credits NOT consumed
 */
import { create } from 'zustand';
import { http } from '../services/http.client';
import { StorageService } from '../services/storage.service';

const CREDITS_KEY = '@oracle/credits';
const ADS_KEY = '@oracle/ads_today';
export const INITIAL_CREDITS = 2000;

export const CREDIT_COSTS = {
  ai_chat:                 50,
  accompagnement:          50,
  dream_interpretation:    80,
  prophetic_consultation: 100,
  prayer_generation:       20,
  audio_preview:           10,
  audio_full:              50,
} as const;

export type CreditAction = keyof typeof CREDIT_COSTS;

export const CREDIT_PACKS = [
  { id: 'starter',  label: 'Pack Départ',   credits: 500,  price: 500,  priceLabel: '500 FCFA' },
  { id: 'standard', label: 'Pack Standard', credits: 2000, price: 1000, priceLabel: '1 000 FCFA', badge: '⭐ Populaire' },
  { id: 'premium',  label: 'Pack Premium',  credits: 5000, price: 2500, priceLabel: '2 500 FCFA', badge: '🏆 Meilleure valeur' },
] as const;

export type CreditPackId = typeof CREDIT_PACKS[number]['id'];

interface CreditsState {
  credits: number;
  adsAvailable: number;
  isLoading: boolean;
  init: () => Promise<void>;
  fetchBalance: () => Promise<void>;
  spend: (action: CreditAction) => Promise<boolean>;
  /** Deduct exactly `wordCount` credits (1 credit = 1 word). Returns false if insufficient. */
  spendWords: (wordCount: number) => Promise<boolean>;
  adReward: () => Promise<void>;
  purchase: (packId: CreditPackId | string, reference: string) => Promise<void>;
  canAfford: (action: CreditAction) => boolean;
  setCredits: (n: number) => void;
}

export const useCreditsStore = create<CreditsState>((set, get) => ({
  credits: INITIAL_CREDITS,
  adsAvailable: 3,
  isLoading: false,

  init: async () => {
    const cached = await StorageService.get<number>(CREDITS_KEY);
    if (cached !== null) set({ credits: cached });
    await get().fetchBalance();
  },

  fetchBalance: async () => {
    try {
      const res = await http.get<{ credits: number; adsAvailable: number }>('/credits');
      if (res?.credits !== undefined) {
        set({ credits: res.credits, adsAvailable: res.adsAvailable ?? 3 });
        await StorageService.set(CREDITS_KEY, res.credits);
      }
    } catch { /* offline — keep local cache */ }
  },

  spend: async (action: CreditAction): Promise<boolean> => {
    const cost = CREDIT_COSTS[action];
    if (get().credits < cost) return false;
    try {
      const res = await http.post<{ credits: number }>('/credits/spend', { amount: cost, description: action });
      const next = res?.credits ?? (get().credits - cost);
      set({ credits: next });
      await StorageService.set(CREDITS_KEY, next);
      return true;
    } catch {
      const next = get().credits - cost;
      set({ credits: next });
      await StorageService.set(CREDITS_KEY, next);
      return true;
    }
  },

  spendWords: async (wordCount: number): Promise<boolean> => {
    if (wordCount <= 0) return true;
    if (get().credits < wordCount) return false;
    try {
      const res = await http.post<{ credits: number }>('/credits/spend', { amount: wordCount, description: 'word_generation' });
      const next = res?.credits ?? (get().credits - wordCount);
      set({ credits: next });
      await StorageService.set(CREDITS_KEY, next);
      return true;
    } catch {
      const next = get().credits - wordCount;
      set({ credits: next });
      await StorageService.set(CREDITS_KEY, next);
      return true;
    }
  },

  adReward: async () => {
    try {
      const res = await http.post<{ credits: number; adsRemaining: number }>('/credits/ad-reward', {});
      if (res?.credits !== undefined) {
        set({ credits: res.credits, adsAvailable: res.adsRemaining });
        await StorageService.set(CREDITS_KEY, res.credits);
        return;
      }
    } catch {}
    const next = get().credits + 100;
    const ads = Math.max(0, get().adsAvailable - 1);
    set({ credits: next, adsAvailable: ads });
    await StorageService.set(CREDITS_KEY, next);
  },

  purchase: async (packId, reference) => {
    try {
      const res = await http.post<{ credits: number }>('/credits/purchase', { pack: packId, reference });
      if (res?.credits !== undefined) {
        set({ credits: res.credits });
        await StorageService.set(CREDITS_KEY, res.credits);
      }
    } catch {}
  },

  canAfford: (action: CreditAction): boolean => get().credits >= CREDIT_COSTS[action],

  setCredits: (n: number) => set({ credits: n }),
}));
